### ISSUE TITLE
Error while running merge command

### ISSUE THREAD

**Issue by tushardave26** [umich-brcf-bioinf/Jacquard#3]
Hello,

I am trying to merge `vcf` generated by `DeepVariant` and `Strlka2`. Unfortunately, I am experiencing an error as described below:

## ERROR
```bash
$ jacquard merge test_files/ test.jq.vcf --include_all --verbose
2019-08-20 14:39:33|DEBUG|merge|Jacquard run begins
2019-08-20 14:39:33|DEBUG|merge|cwd|/home/tushar/projects/Jacquard
2019-08-20 14:39:33|DEBUG|merge|command|merge test_files/ test.jq.vcf --include_all --verbose
2019-08-20 14:39:33|INFO|merge|Jacquard begins (v1.1.2)
2019-08-20 14:39:33|INFO|merge|Saving log to [jacquard.log]
2019-08-20 14:39:33|DEBUG|merge|Writing output to tmp directory [/home/tushar/projects/Jacquard/jacquard.4806.1566326373790115.tmp]
2019-08-20 14:39:33|ERROR|merge|The specified format tag regex [['.*']] would exclude all format tags. Review inputs/usage and try again
2019-08-20 14:39:33|ERROR|merge|Jacquard encountered an unanticipated problem. Please review log file and contact your sysadmin or Jacquard support for assistance.
2019-08-20 14:39:33|DEBUG|merge|Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jacquard/jacquard.py", line 178, in _dispatch
    command.execute(args, execution_context)
  File "/usr/local/lib/python3.6/dist-packages/jacquard/merge.py", line 799, in execute
    merge_vcf_readers)
  File "/usr/local/lib/python3.6/dist-packages/jacquard/merge.py", line 355, in _build_format_tags
    raise utils.JQException(msg, format_tag_regex)
jacquard.utils.utils.JQException: The specified format tag regex [['.*']] would exclude all format tags. Review inputs/usage and try again

2019-08-20 14:39:33|DEBUG|merge|Cleaning up tmp directory
```

## System Info
```bash
# System information
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

## Installation of Jacquard
```bash
$ sudo pip3 install jacquard
```

Can someone help me to solve the issue?

Thanks.

Best regards,
Tushar

**Comment by tushardave26** [comment]
I think I figured out the issue.

`Jacquard` cannot accept `gzipped` `vcf`. You have to `gunzip` the files first. After `gunzip` of the files, `Jaquard` able to merge the files.
